program: new_main.py
method: grid
entity: tromso
project: myesan

parameters:
  gnn_type:
    value: 'originalgin'
  num_layer:
    value: 4
  emb_dim:
    values: [32]
  batch_size:
    values: [32]
  learning_rate:
    values: [0.005]
  decay_rate:
    value: 0.5
  decay_step:
    value: 100
  epochs:
    value: 300
  jk:
    value: 'concat'
  drop_ratio:
    value: 0.
  channels:
    values: ['32-32']
  policy:
    values: ['original']
  model:
    value: 'dss'
  dataset:
    values: ['MUTAG', 'NCI1']

  ex_mask:
    values: ["hard", "soft"]
  ex_epochs:
    values: [10, 20, 30]
  ex_lr:
    values: [0.001, 0.01]
  ex_t1:
    values: [1, 5]
  ex_t2:
    values: [1]
  ex_t3:
    values: [1, 2, 5]
  ex_size:
    values: [0.001, 0.01, 0.1, 0.5]
  ex_noise:
    values: [False, True]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}