program: main.py
method: grid
parameters:
  gnn_type:
    value: 'originalgin'
  num_layer:
    value: 4
  emb_dim:
    values: [32]
  batch_size:
    values: [32]
  learning_rate:
    values: [0.005]
  decay_rate:
    value: 0.5
  decay_step:
    value: 50
  epochs:
    value: 350
  dataset:
    values: ['MUTAG']
  jk:
    value: 'concat'
  drop_ratio:
    value: 0.
  channels:
    values: ['32-32']
  policy:
    values: ['edge_deleted', 'explanation']
  model:
    value: 'dss'
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}